openapi: 3.1.0
info:
  title: Attendance Tracker API
  version: 1.0.0
servers:
  - url: http://localhost:5000
security: []
paths:
  /:
    $ref: paths.yaml
  /absentees:
    $ref: paths/absentees.yaml
  /attendance:
    $ref: paths/attendance.yaml
  /events:
    $ref: paths/events.yaml
  /events/add:
    $ref: paths/events_add.yaml
  /events/edit:
    $ref: paths/events_edit.yaml
  /events/delete/{event_id}:
    $ref: paths/events_delete_{event_id}.yaml
  /students/upload:
    $ref: paths/students_upload.yaml
  /upload:
    $ref: paths/upload.yaml
